.Dd January 21, 2021
.Dt RCLONE-CONFIG 1
.Os
.Sh NAME
.Nm rclone-config
.Nd configure storage system
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION

.Ss 1Fichier
.Ss Alias
.Ss Amazon Drive
.Ss Amazon S3
.Ss Backblaze B2
.Ss Box
.Ss Cache
.Ss Chunker
.Ss Citrix ShareFile
.Ss Compress
.Ss Crypt
.Ss DigitalOcean Spaces
.Ss Dropbox
.Ss Enterprise File Fabric
.Ss FTP
.Ss Google Cloud Storage
.Ss Google Drive
.Ss Google Photos
.Ss HDFS
.Ss HTTP
.Ss Hubic
.Ss Jottacloud / GetSky.no
.Ss Koofr
.Ss Mail.ru Cloud
.Ss Mega
.Ss Memory
.Ss Microsoft Azure Blob Storage
.Ss Microsoft OneDrive
.Ss OpenStack Swift / Rackspace Cloudfiles / Memset Memstore
.Ss OpenDrive
.Ss Pcloud
.Ss premiumize.me
.Ss put.io
.Ss QingStor
.Ss Seafile
.Ss SFTP
.Ss SugarSync
.Ss Tardigrade
.Ss Union
.Ss WebDAV
.Ss Yandex Disk
.Ss Zoho WorkDrive
.Ss The local filesystem
